2023-07-24 14:54:08,403 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 9 hosts
2023-07-24 14:54:08,406 - nornir.core.task -    ERROR -      start() - Host 'cisco3': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,407 - nornir.core.task -    ERROR -      start() - Host 'cisco4': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,409 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,409 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,410 - nornir.core.task -    ERROR -      start() - Host 'arista1': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,412 - nornir.core.task -    ERROR -      start() - Host 'arista2': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,412 - nornir.core.task -    ERROR -      start() - Host 'arista3': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,413 - nornir.core.task -    ERROR -      start() - Host 'arista4': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:08,413 - nornir.core.task -    ERROR -      start() - Host 'srx2': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:39,200 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-24 14:54:39,205 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:54:39,205 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 8, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:57:37,061 -  nornir.core -  WARNING -        run() - Task 'render_config' has not been run – 0 hosts selected
2023-07-24 14:58:53,062 -  nornir.core -  WARNING -        run() - Task 'render_config' has not been run – 0 hosts selected
2023-07-24 14:59:46,487 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-24 14:59:46,492 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 9, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 14:59:46,493 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'render_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 9, in render_config
    bgp_multi_result = task.run(task="template_file", template="bgp.j2", path=template_path, **task.host)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 161, in run
    run_task = Task(
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 55, in __init__
    self.name = name or task.__name__
AttributeError: 'str' object has no attribute '__name__'

2023-07-24 15:01:32,713 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-24 15:02:12,625 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-24 15:02:14,653 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'template_file' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir_jinja2/plugins/tasks/template_file.py", line 43, in template_file
    text = t.render(host=task.host, **kwargs)
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "nxos/bgp.j2", line 4, in top-level template code
    remote-as {{ bgp_remote_as_asn }}
jinja2.exceptions.UndefinedError: 'bgp_remote_as_asn' is undefined

2023-07-24 15:03:32,417 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-24 15:03:59,526 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:16:38,293 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:17:03,203 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:17:03,211 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:17:03,213 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:17:03,214 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:17:16,384 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:17:16,411 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:17:16,418 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:17:16,421 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:17:16,422 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:18:11,593 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:18:11,622 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:18:11,629 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:18:11,632 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:18:11,633 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 29, in deploy_config
    with open(bgp_filename, "r") as fbgp, (int_filename, "r") as fint:
AttributeError: __enter__

2023-07-25 14:19:14,547 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:19:14,575 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:19:14,582 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:20:10,713 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:20:10,741 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:20:10,748 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:20:10,751 - nornir.core.task -    ERROR -      start() - Host 'nxos1': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 32, in deploy_config
    configure += "\n"
UnboundLocalError: local variable 'configure' referenced before assignment

2023-07-25 14:20:10,752 - nornir.core.task -    ERROR -      start() - Host 'nxos2': task 'deploy_config' failed with traceback:
Traceback (most recent call last):
  File "/home/delbrugge/VENV/py3_venv/lib/python3.9/site-packages/nornir/core/task.py", line 99, in start
    r = self.task(self, **self.params)
  File "/home/delbrugge/nornir-class/lesson_5/exercise_5/ex5a.py", line 32, in deploy_config
    configure += "\n"
UnboundLocalError: local variable 'configure' referenced before assignment

2023-07-25 14:20:35,186 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:20:35,213 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:20:35,221 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-25 14:21:20,534 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-25 14:21:20,562 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-25 14:21:20,569 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-26 13:28:12,417 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-26 13:28:12,446 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-26 13:28:12,455 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-26 13:33:33,376 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-26 13:33:33,406 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-26 13:33:33,415 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-26 13:34:42,370 -  nornir.core -     INFO -        run() - Running task 'render_config' with args {} on 2 hosts
2023-07-26 13:34:42,398 -  nornir.core -     INFO -        run() - Running task 'write_configs' with args {} on 2 hosts
2023-07-26 13:34:42,414 -  nornir.core -     INFO -        run() - Running task 'deploy_config' with args {} on 2 hosts
2023-07-26 13:35:10,342 -  nornir.core -     INFO -        run() - Running task 'verify_bgp_status' with args {} on 2 hosts
